### ISSUE TITLE
purge command tested messages error

### ISSUE THREAD

**Issue by Salvi0** [aternosorg/modbot#213] opened 2021-03-03 17:41 UTC
this issue is directly related to the 2 weeks old messages. (bots cannot ddelete them).
btw the bot output had an error when he tried to delete messages in an empty channel or a channel were the most recent messages was at least 2 weeks old.

[proof](https://ezic.report.sys.salvi0.xyz/media/Discord_2vk5SSsHDQ.png)

i also self-hosted the bot, but when i tried to fix the issue i failed.

log output below.

[proof2](https://ezic.report.sys.salvi0.xyz/media/Code_4pJg63FX9p.png)

**Comment by JulianVennen** [comment] 2021-03-03 19:31
I was not able to reproduce the problem in channels with messages that are older than 14 days.
The problem with empty channels is fixed in #214

**Comment by Salvi0** [comment] 2021-03-03 21:43
if is possible i can contact you via discord itself so i can try to replicate the bug.

**Comment by Salvi0** [comment] 2021-03-03 22:28
nvm i will wait the fix. Btw in the meantime, how the protectedroles should work?

**Comment by JulianVennen** [comment] 2021-03-07 17:56
Purging in empty channels should be fixed now

**Comment by Salvi0** [comment] 2021-03-08 00:03
Confirmed (purge one). Now for the protected roles, how they works? I mean they exclude someone from being automoderated? Or they are a way to no let any user change their permissions?

**Comment by JulianVennen** [comment] 2021-03-08 09:17
protected roles are excluded from auto-moderation and also cant be targeted by moderation commands

**Closed by JulianVennen** 2021-03-08 09:17 UTC
